name: "Get changed files"
description: "Get changed files"
inputs:
  github-token:
    description: 'Who to greet'
    required: true
    default: 'World'
  files-count:
    description: 'Who to greet'
    required: true
    default: 'World'
  page-size:
    description: 'Who to greet'
    required: true
    default: '30'

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        for ((i=1; i<=$((inputs.files-count/inputs.page-size));i++));
         do curl --header 'authorization: Bearer ${{ inputs.github-token }}' \
          --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/files?per_page=$inputs.page-size&page=$i > "./content$i.json";
        done;
        cat ./content*.json | jq -s 'add' > ${{ github.workspace }}/changed-files.json
