name: Get changed files
description: Get changed files

runs:
  using: composite
  steps:
    - name: Get changed files
      shell: bash
      run: |
        gh api \
          -H "Accept: application/vnd.github+json" \
          "/repos/DevExpress/devextreme-demos/pulls/2584/files" --paginate \
          --jq '.[] | {filename:.filename}' | jq -s > changed-files.json
