name: "Get changed files"
description: "Get changed files"
inputs:
  github-token:
    description: 'GitHub API token'
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        page_size=30
        for ((i=1; i<=$((${{github.event.pull_request.changed_files}}/$page_size));i++));
         do curl --header 'authorization: Bearer ${{ inputs.github-token }}' \
          --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/files?per_page=$page_size&page=$i > "./content$i.json";
        done;
        
        echo DONE!!!!!!!
        cat ./content*.json | jq -s 'add'
        echo SAVE!!!!!!!
        cat ./content*.json | jq -s 'add' > ${{ github.workspace }}/changed-files.json
