name: "Get changed files"
description: "Get changed files"

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        total=${{github.event.pull_request.changed_files}};
        page_size=10;
        for ((i=1; i<=$((total/page_size));i++));
         do curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/files?per_page=$page_size&page=$i > "./content$i.json";
        done;
        cat ./content*.json | jq -s 'add' > ${{ github.workspace }}/changed-files.json
