name: "Get changed files"
description: "Get changed files"
inputs:
  github-token:
    description: 'GitHub API token'
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        gh api \
          -H "Accept: application/vnd.github+json" \
          "/repos/{owner}/{repo}/pulls/${{github.event.pull_request.number}}/files?per_page=100" --paginate --jq 'map({filename})' >> changed-files.json
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
