name: Get Changed Files

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build DevExtreme
    timeout-minutes: 15

    steps:
      - name: Get changed files
        run: |
          total=github.event.pull_request.changed_files;
          page_size=10;
          for ((i=1; i<$((total/page_size + 1));i++));
           do curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/files?per_page=$page_size&page=$i
          done;
          cat ./content*.json | jq -s 'add' >| ./out.json
          cat ./out.json
