name: Get Changed Files

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build DevExtreme
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3

      - name: Get changed files
        uses: ./.github/actions/get-changed-files
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files-count: ${{github.event.pull_request.changed_files}}
          page-size: '30'

      - name: Copy artifacts
        uses: actions/upload-artifact@v3
        with:
          name: changed-files
          path: ${{ github.workspace }}/changed-files.json
          if-no-files-found: ignore
