name: Get Changed Files

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build DevExtreme
    timeout-minutes: 15

    steps:
      - name: Get changed files
        run: |
          echo "Changed files count: ${{github.event.pull_request.changed_files}}"
          curl --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
            --url https://api.github.com/repos/${{github.repository}}/pulls/${{github.event.pull_request.number}}/files
